config/routes.rb
Ses::Application.routes.draw do
  resources :progresses

end

app/models/curriculum.rb
class Curriculum < ActiveRecord::Base
end

app/models/progress.rb
class Progress < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController
  before_action :set_progress, only: [:show, :edit, :update, :destroy]

  # GET /progresses
  # GET /progresses.json
  def index
    @progresses = Progress.all
  end

  # GET /progresses/1
  # GET /progresses/1.json
  def show
  end

  # GET /progresses/new
  def new
    @progress = Progress.new
  end

  # GET /progresses/1/edit
  def edit
  end

  # POST /progresses
  # POST /progresses.json
  def create
    @progress = Progress.new(progress_params)

    respond_to do |format|
      if @progress.save
        format.html { redirect_to @progress, notice: 'Progress was successfully created.' }
        format.json { render action: 'show', status: :created, location: @progress }
      else
        format.html { render action: 'new' }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progresses/1
  # PATCH/PUT /progresses/1.json
  def update
    respond_to do |format|
      if @progress.update(progress_params)
        format.html { redirect_to @progress, notice: 'Progress was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progresses/1
  # DELETE /progresses/1.json
  def destroy
    @progress.destroy
    respond_to do |format|
      format.html { redirect_to progresses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress
      @progress = Progress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def progress_params
      params.require(:progress).permit(:student_id, :student_name, :goal, :goal_month, :goal_week, :progress_date, :due_date, :progress)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ses</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/progresses/_form.html.erb
<%= form_for(@progress) do |f| %>
  <% if @progress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@progress.errors.count, "error") %> prohibited this progress from being saved:</h2>

      <ul>
      <% @progress.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :student_name %><br>
    <%= f.text_field :student_name %>
  </div>
  <div class="field">
    <%= f.label :goal %><br>
    <%= f.text_field :goal %>
  </div>
  <div class="field">
    <%= f.label :goal_month %><br>
    <%= f.text_field :goal_month %>
  </div>
  <div class="field">
    <%= f.label :goal_week %><br>
    <%= f.text_field :goal_week %>
  </div>
  <div class="field">
    <%= f.label :progress_date %><br>
    <%= f.datetime_select :progress_date %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :progress %><br>
    <%= f.number_field :progress %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/progresses/edit.html.erb
<h1>Editing progress</h1>

<%= render 'form' %>

<%= link_to 'Show', @progress %> |
<%= link_to 'Back', progresses_path %>

app/views/progresses/index.html.erb
<h1>Listing progresses</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Student name</th>
      <th>Goal</th>
      <th>Goal month</th>
      <th>Goal week</th>
      <th>Progress date</th>
      <th>Due date</th>
      <th>Progress</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @progresses.each do |progress| %>
      <tr>
        <td><%= progress.student_id %></td>
        <td><%= progress.student_name %></td>
        <td><%= progress.goal %></td>
        <td><%= progress.goal_month %></td>
        <td><%= progress.goal_week %></td>
        <td><%= progress.progress_date %></td>
        <td><%= progress.due_date %></td>
        <td><%= progress.progress %></td>
        <td><%= link_to 'Show', progress %></td>
        <td><%= link_to 'Edit', edit_progress_path(progress) %></td>
        <td><%= link_to 'Destroy', progress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Progress', new_progress_path %>

app/views/progresses/new.html.erb
<h1>New progress</h1>

<%= render 'form' %>

<%= link_to 'Back', progresses_path %>

app/views/progresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @progress.student_id %>
</p>

<p>
  <strong>Student name:</strong>
  <%= @progress.student_name %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @progress.goal %>
</p>

<p>
  <strong>Goal month:</strong>
  <%= @progress.goal_month %>
</p>

<p>
  <strong>Goal week:</strong>
  <%= @progress.goal_week %>
</p>

<p>
  <strong>Progress date:</strong>
  <%= @progress.progress_date %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @progress.due_date %>
</p>

<p>
  <strong>Progress:</strong>
  <%= @progress.progress %>
</p>

<%= link_to 'Edit', edit_progress_path(@progress) %> |
<%= link_to 'Back', progresses_path %>